workloads:
  - type: RemoteControlDevice
    args:
      stick_dead_zone: 0.2

  - type: MujocoSimpleRc
    name: simple_rc
    args:
      tick_rate_hz: 30
      data_bindings:
        - linear_speed -> balance_pid.setpoint
        - yaw_speed -> steering_mixer.turn_input

  - type: AxisToAngleTransformer
    name: pitch_transformer
    args:
      axis_name: z
      data_bindings:
        - input_vector <- mujoco_sim.body_axis_sensor

  - type: PidControl
    name: balance_pid
    args:
      tick_rate_hz: 100
      kp: 1.2
      ki: 0.005
      kd: 0.005
      data_bindings:      
        - measured <- pitch_transformer.output_value
        - control_output -> steering_mixer.balance_input

  - type: SteeringMixer
    name: steering_mixer
    args:
      tick_rate_hz: 100
      data_bindings:
        - left_motor -> mujoco_sim.motor_left_wheel
        - right_motor -> mujoco_sim.motor_right_wheel

  - type: MujocoSimulator
    name: mujoco_sim
    args:
      xml_path: "mujoco_scene.xml"
      display_enabled: True

  - type: MqttUpdate
    name: comms
    args:
      broker_host: localhost
      broker_port: 1883

  - type: ConsoleUpdate
    name: console
    args:
      tick_rate_hz: 2
